# Generated by Django 5.0.4 on 2024-06-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educapp', '0002_quiz_quiztitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevTeam',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
            ],
        ),
    ]
