# Generated by Django 5.0.4 on 2024-06-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educapp', '0003_devteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='devteam',
            name='address',
            field=models.CharField(default='Damilag, Manolo Fortich, Bukidnon', max_length=200),
        ),
    ]
